CREATE DATABASE RegistroAcademico; 
GO
USE RegistroAcademico;
GO

CREATE TABLE Estado(
Id TINYINT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(100) NOT NULL 
);

CREATE TABLE Carrera(
Id SMALLINT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(100) NOT NULL,
IdEstado TINYINT FOREIGN KEY REFERENCES Estado(Id)
); 

CREATE TABLE Estudiante(
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(100) NOT NULL,
Apellido VARCHAR(100) NOT NULL,
Direccion VARCHAR(200) NOT NULL,
Telefono VARCHAR(100) NOT NULL,
IdCarrera SMALLINT FOREIGN KEY REFERENCES Carrera(Id),
IdEstado TINYINT FOREIGN KEY REFERENCES Estado(Id)
); 
