<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ESFE.RegistroAcademico.EntidadesDeNegocio\ESFE.RegistroAcademico.EntidadesDeNegocio.csproj" />
    <ProjectReference Include="..\ESFE.RegistroAcademico.LogicaDeNegocios\ESFE.RegistroAcademico.LogicaDeNegocios.csproj" />
  </ItemGroup>

</Project>